### ISSUE TITLE
The tutorial url does not work anymore https://www.lizeyan.me/Install-K8s-6af38c1ff4e04b6d9ea9387a7a198b5b

### ISSUE THREAD

**Issue by phamquiluan** [lizeyan/train-ticket#5]
The tutorial url does not work anymore https://www.lizeyan.me/Install-K8s-6af38c1ff4e04b6d9ea9387a7a198b5b

**Comment by phamquiluan** [comment]
@lizeyan please help me :crying_cat_face:

**Comment by lizeyan** [comment]
> @lizeyan please help me 😿

Try this: https://www.notion.so/Install-K8s-6af38c1ff4e04b6d9ea9387a7a198b5b

**Comment by phamquiluan** [comment]
Thank you @lizeyan. 

Another concern. It seems like the README below is outdated. Basically, after `cd train-ticket`, there is no `es-jaeger.yml` file. 

Please help me :bow: 

https://github.com/lizeyan/train-ticket/tree/master/deployment/kubernetes-manifests/k8s-with-jaeger
![image](https://user-images.githubusercontent.com/24642166/234442451-ad9872ca-13a5-4c2c-a8f5-9efb57db3edf.png)

**Comment by lizeyan** [comment]
`es-jaeger.yml` is here: https://github.com/lizeyan/train-ticket/tree/master/deployment/kubernetes-manifests/k8s-with-jaeger
