### ISSUE TITLE
Do we really need the persistent volume?

### ISSUE THREAD

**Issue by phamquiluan** [lizeyan/train-ticket#6]
HI @lizeyan, thank you for your work!

As I read the code, I see you develop the persistent volume to avoid the creation of users every time. And I had a hard time dealing with this... so I have some questions.
Q1: Is there any other purpose for the persistent volume?
Q2: Can we perform the fault injection without the persistent volume?

**Comment by lizeyan** [comment]
Creating users could fail after restarting Train Ticket. I restart Train Ticket automatically every midnight, so I need to avoid creating users each time.

**Comment by phamquiluan** [comment]
Thank you so much @lizeyan <3
